apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jobboard.fullname" . }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "jobboard.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.backend.env.NODE_ENV | quote }}
  PORT: {{ .Values.backend.port | quote }}
  HOST: "0.0.0.0"
  LOG_LEVEL: {{ .Values.backend.env.LOG_LEVEL | quote }}
  POSTGRES_HOST: "{{ include "jobboard.fullname" . }}-postgres"
  POSTGRES_PORT: {{ .Values.postgres.port | quote }}
  POSTGRES_DB: {{ .Values.postgres.auth.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.auth.username | quote }}
  REDIS_HOST: "{{ include "jobboard.fullname" . }}-redis"
  REDIS_PORT: {{ .Values.redis.port | quote }}
  REDIS_URL: "redis://{{ include "jobboard.fullname" . }}-redis:{{ .Values.redis.port }}"
  RATE_LIMIT_WINDOW_MS: {{ .Values.backend.env.RATE_LIMIT_WINDOW_MS | quote }}
  RATE_LIMIT_MAX: {{ .Values.backend.env.RATE_LIMIT_MAX | quote }}
  CORS_ORIGINS: "http://localhost:3000,http://{{ include "jobboard.fullname" . }}-frontend:3000,https://{{ (index .Values.ingress.hosts 0).host }}"
  VITE_API_URL: "/api"
