{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jobboard.fullname" . }}-postgres
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "jobboard.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
      name: postgres
  clusterIP: None
  selector:
    {{- include "jobboard.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}
