{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jobboard.fullname" . }}-redis
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "jobboard.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
      name: redis
  selector:
    {{- include "jobboard.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
