apiVersion: v1
kind: ResourceQuota
metadata:
  name: jobboard-quota
  namespace: jobboard
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    pods: "30"
    services: "10"
    persistentvolumeclaims: "5"
