apiVersion: v1
kind: Secret
metadata:
  name: jobboard-secret
  namespace: jobboard
  labels:
    app.kubernetes.io/name: jobboard-secret
    app.kubernetes.io/part-of: jobboard-platform
type: Opaque
stringData:
  POSTGRES_PASSWORD: "jobboard_secure_password_dev_only"
  DATABASE_URL: "postgresql://jobboard_user:jobboard_secure_password_dev_only@jobboard-postgres:5432/jobboard_db"
  JWT_SECRET: "dev_jwt_secret_change_in_production_min_32_characters_long_12345"
