apiVersion: v1
kind: ServiceAccount
metadata:
  name: jobboard-app-sa
  namespace: jobboard
  labels:
    app.kubernetes.io/name: jobboard-app-sa
    app.kubernetes.io/part-of: jobboard-platform
automountServiceAccountToken: false
